### PR TITLE
Issue #28616: Make Item UPC Code unique and tidy up demo data

### PR DESCRIPTION
**Pull request by andersdd**

### CODE REVIEW

**Comment by sindhupriyaav** [comment]
Unable to perform UAT. Observed the following errors while building database from pull request branch.

Error:
xtuple@Ubuntu10:~/src/xtuple$ sudo ./scripts/build_app.js -d 28616
building client core
building crm
building project
building sales
building billing
building purchasing
building oauth2
building inventory
building manufacturing
building distribution
[ '/home/xtuple/src/xtuple/foundation-database',
  '/home/xtuple/src/xtuple/lib/orm',
  '/home/xtuple/src/xtuple',
  '/home/xtuple/src/xtuple/enyo-client/extensions/source/crm',
  '/home/xtuple/src/xtuple/enyo-client/extensions/source/project',
  '/home/xtuple/src/xtuple/enyo-client/extensions/source/sales',
  '/home/xtuple/src/xtuple/enyo-client/extensions/source/billing',
  '/home/xtuple/src/xtuple/enyo-client/extensions/source/purchasing',
  '/home/xtuple/src/xtuple/enyo-client/extensions/source/oauth2',
  '/home/xtuple/src/private-extensions/source/inventory',
  '/home/xtuple/src/private-extensions/source/manufacturing',
  '/home/xtuple/src/private-extensions/source/distribution' ]
[ '/home/xtuple/src/xtuple/foundation-database',
  '/home/xtuple/src/xtuple/lib/orm',
  '/home/xtuple/src/xtuple',
  '/home/xtuple/src/xtuple/enyo-client/extensions/source/crm',
  '/home/xtuple/src/xtuple/enyo-client/extensions/source/project',
  '/home/xtuple/src/xtuple/enyo-client/extensions/source/sales',
  '/home/xtuple/src/xtuple/enyo-client/extensions/source/billing',
  '/home/xtuple/src/xtuple/enyo-client/extensions/source/purchasing',
  '/home/xtuple/src/xtuple/enyo-client/extensions/source/oauth2',
  '/home/xtuple/src/private-extensions/source/commercialcore',
  '/home/xtuple/src/private-extensions/source/inventory',
  '/home/xtuple/src/private-extensions/source/manufacturing',
  '/home/xtuple/src/private-extensions/source/distribution' ]
Saved PEGjs parser Javascript to  ../lib/orm/source/xt/javascript/parsemetasql.sql
Saved PEGjs parser Javascript to  ../lib/orm/source/xt/javascript/parseediprofile.sql
No built client file for commercialcore. There is probably no client-side code in the extension.
Applying build to database 28616
Cannot install file  /home/xtuple/src/xtuple/scripts/output/build_28616.sql
See errors in  /home/xtuple/src/xtuple/scripts/output/build_28616.sql.log

################################################################################
# ERROR: psql stderr OUTPUT LAST 20 LINES OF: /home/xtuple/src/xtuple/scripts/output/build_28616.sql.log
################################################################################

 psql:/home/xtuple/src/xtuple/scripts/output/build_28616.sql:36114: NOTICE:  function getunassignedaccntid() does not exist, skipping
psql:/home/xtuple/src/xtuple/scripts/output/build_28616.sql:39252: NOTICE:  drop cascades to rule _INSERT on view api.itemcost
psql:/home/xtuple/src/xtuple/scripts/output/build_28616.sql:39333: NOTICE:  function invadjustment(pg_catalog.int4,pg_catalog.numeric,text,text) does not exist, skipping
psql:/home/xtuple/src/xtuple/scripts/output/build_28616.sql:39335: NOTICE:  function invadjustment(pg_catalog.int4,pg_catalog.numeric,text,text,pg_catalog.timestamptz) does not exist, skipping
psql:/home/xtuple/src/xtuple/scripts/output/build_28616.sql:39337: NOTICE:  function invadjustment(pg_catalog.int4,pg_catalog.numeric,text,text,pg_catalog.timestamptz,pg_catalog.numeric) does not exist, skipping
psql:/home/xtuple/src/xtuple/scripts/output/build_28616.sql:39928: NOTICE:  function issuetoshipping(text,pg_catalog.int4,pg_catalog.numeric,pg_catalog.int4,pg_catalog.timestamptz,pg_catalog.int4) does not exist, skipping
psql:/home/xtuple/src/xtuple/scripts/output/build_28616.sql:40279: NOTICE:  function issuewomaterial(pg_catalog.int4,pg_catalog.numeric,pg_catalog.int4,pg_catalog.timestamptz) does not exist, skipping
psql:/home/xtuple/src/xtuple/scripts/output/build_28616.sql:40288: NOTICE:  function issuewomaterial(pg_catalog.int4,pg_catalog.numeric,pg_catalog.int4,pg_catalog.timestamptz,pg_catalog.int4) does not exist, skipping
psql:/home/xtuple/src/xtuple/scripts/output/build_28616.sql:40564: NOTICE:  function itemcharprice(pg_catalog.int4,pg_catalog.int4,text,pg_catalog.int4,pg_catalog.int4,pg_catalog.numeric,pg_catalog.int4,date,date) does not exist, skipping
psql:/home/xtuple/src/xtuple/scripts/output/build_28616.sql:41049: NOTICE:  function itemipsprice(pg_catalog.int4,pg_catalog.int4,pg_catalog.int4,pg_catalog.numeric,pg_catalog.int4,pg_catalog.int4,pg_catalog.int4,date,date,pg_catalog.int4) does not exist, skipping
psql:/home/xtuple/src/xtuple/scripts/output/build_28616.sql:41943: NOTICE:  function listprice(pg_catalog.int4,pg_catalog.int4,pg_catalog.int4,pg_catalog.int4) does not exist, skipping
psql:/home/xtuple/src/xtuple/scripts/output/build_28616.sql:42216: NOTICE:  function lowercost(pg_catalog.int4,text) does not exist, skipping
psql:/home/xtuple/src/xtuple/scripts/output/build_28616.sql:49209: NOTICE:  function postinvtrans(pg_catalog.int4,text,pg_catalog.numeric,text,text,text,text,text,pg_catalog.int4,pg_catalog.int4,pg_catalog.int4,pg_catalog.timestamptz,pg_catalog.numeric,pg_catalog.int4) does not exist, skipping
psql:/home/xtuple/src/xtuple/scripts/output/build_28616.sql:62497: NOTICE:  drop cascades to rule _UPDATE on view api.itemcost
psql:/home/xtuple/src/xtuple/scripts/output/build_28616.sql:62620: NOTICE:  function updatelowerusercosts(pg_catalog.int4) does not exist, skipping
psql:/home/xtuple/src/xtuple/scripts/output/build_28616.sql:62722: NOTICE:  function updatememotax(text,text,pg_catalog.int4,pg_catalog.int4,date,pg_catalog.int4,pg_catalog.numeric) does not exist, skipping
psql:/home/xtuple/src/xtuple/scripts/output/build_28616.sql:65957: ERROR:  could not create unique index "item_item_upccode_key"
DETAIL:  Key (item_upccode)=() is duplicated.
CONTEXT:  SQL statement "alter table public.item add constraint item_item_upccode_key UNIQUE(item_upccode);"
PL/pgSQL function xt.add_constraint(text,text,text,text) line 22 at EXECUTE statement
 
################################################################################
# END OF psql stderr LOG OUTPUT ################################################
################################################################################


Command failed:  Error: Command failed: 
    at ChildProcess.exithandler (child_process.js:658:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5) { [Error: Command failed: ] killed: false, code: 3, signal: null }
{ [Error: Command failed: ] killed: false, code: 3, signal: null }

**Comment by gilmoskowitz** [comment]
+1

@sindhupriyaav - The process used for UAT includes upgrading an older database with existing `item` records using `build_app.js`. The Updater package [has a prerequisite check](https://github.com/xtuple/xtuple/pull/2852/files#diff-d561698e55df9b1110267385b45dd729R95) that points out the potential failure but there is no similar mechanism in `build_app.js`.

For the time being, run the following against the test database before running `build_app.js`:
```SQL
UPDATE item SET item_upccode = NULL WHERE item_upccode = '';
```

**Comment by lokeshsh** [comment]
Performed UAT:
On running the following Command on the database:
" UPDATE item SET item_upccode = NULL WHERE item_upccode = ''; "

Observed the following error:

ERROR:  You do not have privileges to maintain Items.
********** Error **********

ERROR: You do not have privileges to maintain Items.
SQL state: P0001

**Comment by davidbeauchamp** [comment]
@lokeshsh please make sure that you are connecting as the admin user from pgAdmin, the default is the "postgres" user which does not have privileges inside the database.

**Comment by rkannadevara** [comment]
Performed UAT: 
executed the below query on the database before doing build_app.js and query executed successfully as admin user:
               UPDATE item SET item_upccode = NULL WHERE item_upccode = '';

Observed the below error while doing build_app.js on database:

Applying build to database upccode
Cannot install file  /home/xtuple/src/xtuple/scripts/output/build_upccode.sql
See errors in  /home/xtuple/src/xtuple/scripts/output/build_upccode.sql.log

################################################################################
# ERROR: psql stderr OUTPUT LAST 20 LINES OF: /home/xtuple/src/xtuple/scripts/output/build_upccode.sql.log
################################################################################

 psql:/home/xtuple/src/xtuple/scripts/output/build_upccode.sql:18547: NOTICE:  function createpriv(text,text,text) does not exist, skipping
psql:/home/xtuple/src/xtuple/scripts/output/build_upccode.sql:23976: NOTICE:  function deletewo(pg_catalog.int4,pg_catalog.bool) does not exist, skipping
psql:/home/xtuple/src/xtuple/scripts/output/build_upccode.sql:25715: NOTICE:  function enterporeturn(pg_catalog.int4,pg_catalog.numeric,pg_catalog.int4,pg_catalog.int4) does not exist, skipping
psql:/home/xtuple/src/xtuple/scripts/output/build_upccode.sql:36114: NOTICE:  function getunassignedaccntid() does not exist, skipping
psql:/home/xtuple/src/xtuple/scripts/output/build_upccode.sql:39252: NOTICE:  drop cascades to rule _INSERT on view api.itemcost
psql:/home/xtuple/src/xtuple/scripts/output/build_upccode.sql:39928: NOTICE:  function issuetoshipping(text,pg_catalog.int4,pg_catalog.numeric,pg_catalog.int4,pg_catalog.timestamptz,pg_catalog.int4) does not exist, skipping
psql:/home/xtuple/src/xtuple/scripts/output/build_upccode.sql:40279: NOTICE:  function issuewomaterial(pg_catalog.int4,pg_catalog.numeric,pg_catalog.int4,pg_catalog.timestamptz) does not exist, skipping
psql:/home/xtuple/src/xtuple/scripts/output/build_upccode.sql:40288: NOTICE:  function issuewomaterial(pg_catalog.int4,pg_catalog.numeric,pg_catalog.int4,pg_catalog.timestamptz,pg_catalog.int4) does not exist, skipping
psql:/home/xtuple/src/xtuple/scripts/output/build_upccode.sql:40564: NOTICE:  function itemcharprice(pg_catalog.int4,pg_catalog.int4,text,pg_catalog.int4,pg_catalog.int4,pg_catalog.numeric,pg_catalog.int4,date,date) does not exist, skipping
psql:/home/xtuple/src/xtuple/scripts/output/build_upccode.sql:41049: NOTICE:  function itemipsprice(pg_catalog.int4,pg_catalog.int4,pg_catalog.int4,pg_catalog.numeric,pg_catalog.int4,pg_catalog.int4,pg_catalog.int4,date,date,pg_catalog.int4) does not exist, skipping
psql:/home/xtuple/src/xtuple/scripts/output/build_upccode.sql:41943: NOTICE:  function listprice(pg_catalog.int4,pg_catalog.int4,pg_catalog.int4,pg_catalog.int4) does not exist, skipping
psql:/home/xtuple/src/xtuple/scripts/output/build_upccode.sql:42216: NOTICE:  function lowercost(pg_catalog.int4,text) does not exist, skipping
psql:/home/xtuple/src/xtuple/scripts/output/build_upccode.sql:49209: NOTICE:  function postinvtrans(pg_catalog.int4,text,pg_catalog.numeric,text,text,text,text,text,pg_catalog.int4,pg_catalog.int4,pg_catalog.int4,pg_catalog.timestamptz,pg_catalog.numeric,pg_catalog.int4) does not exist, skipping
psql:/home/xtuple/src/xtuple/scripts/output/build_upccode.sql:62497: NOTICE:  drop cascades to rule _UPDATE on view api.itemcost
psql:/home/xtuple/src/xtuple/scripts/output/build_upccode.sql:62620: NOTICE:  function updatelowerusercosts(pg_catalog.int4) does not exist, skipping
psql:/home/xtuple/src/xtuple/scripts/output/build_upccode.sql:62722: NOTICE:  function updatememotax(text,text,pg_catalog.int4,pg_catalog.int4,date,pg_catalog.int4,pg_catalog.numeric) does not exist, skipping
psql:/home/xtuple/src/xtuple/scripts/output/build_upccode.sql:65961: ERROR:  could not create unique index "item_item_upccode_key"
DETAIL:  Key (item_upccode)=(1234-4567) is duplicated.
CONTEXT:  SQL statement "alter table public.item add constraint item_item_upccode_key UNIQUE(item_upccode);"
PL/pgSQL function xt.add_constraint(text,text,text,text) line 22 at EXECUTE statement
 
################################################################################
# END OF psql stderr LOG OUTPUT ################################################
################################################################################


Command failed:  Error: Command failed: 
    at ChildProcess.exithandler (child_process.js:658:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5) { [Error: Command failed: ] killed: false, code: 3, signal: null }
{ [Error: Command failed: ] killed: false, code: 3, signal: null }

**Comment by andersdd** [comment]
Modified so that the uniqueness is controlled by a Product -> Setting which should resolve test database issues.

**Pull request merged**
