### PR TITLE
Issue #30315: Repeated reversals add extraneous tags

### PR DESCRIPTION
**Pull request by andersdd**

### CODE REVIEW

**Comment by harithamekala** [comment]
Performed UAT: Observed that ‘[Rev]’ is still displayed in customer workbench screen while reversing the cash receipt for 1st time.

Also observed that on reversing the cash receipt from 2nd time application is crashed. Please refer to the below attached screenshot ‘Reverse.png’.

reverse

**Comment by andersdd** [comment]
@harithamekala The [REV] is supposed to be there.  What the change does is prevent multiple reversals continually adding extra tags - for example [REV] [REV] [REV]

This was a simple function change. I find it difficult to believe it results in an application crash - any problems should just throw up an error message.  I suggest you look deeper into any logs or steps to reproduce.

**Comment by rkannadevara** [comment]
Performed UAT: Observed that application is crashed on reversing the invoice for 3rd time. Please refer the steps we followed to reproduce:

1.	Create and do the buildapp masterref database from pull request branch using below commands:
 
          a)createdb –h localhost –U postgres dbname
          b)pg_restore –host=localhost –port=5432 –username=postgres –d dbname “Path of 4.11.0RC 
              masterref backup file”
           c) cd xtuple
           d) sudo scripts/build_app.js –d dbname
2.	Now login to the 4.11.1 latest nightly build(2017-08-02) on Windows environment using above c 
         

created database.
3.	Create and post invoice for a customer ‘TTOYS’ with item ‘YTRUCK1’ of quantity ‘100’.
4.	Create and post another invoive for customer ‘TTOYS’ with item ‘BTRUCK1’ of quantity ‘100’.
5.	Now create and post cash receipt by applying above 2 invoices.
6.	Now open ‘Applications’ screen from Accounting-Accounts Receivable-Reports-Applications.
7.	Observe that above created 2 invoices are displayed.
8.	Now Select ‘Reverse Application’ option from context menu of one invoice.
9.	Observe that reversal invoice is created in ‘A/R Applications’ screen.
10.	Now observe that one credit memo is created in ‘Accounting’ tab of ‘Customer’ workbench with out any tag say [REV].
11.	Now again the click on ‘Reverse Application’ on above reversal invoice in ‘A/R Applications’ screen.
12.	Observe that another credit memo is created in ‘Accounting’ tab of ‘Customer’ workbench screen with one tag [REV].
13.	Now again click on ‘Reversal Application’ option on above created reversal invoice in ‘A/R Applications’ screen.
14.	Observe that application is not responding and crashed. Please refer the video recording placed in xTuple dropbox drive under 'xtuple' folder.

**Comment by andersdd** [comment]
Bit of an unusual/unrealistic scenario attempting to reverse the application so many times, but I can confirm reproducing the application crash.

**Comment by gilmoskowitz** [comment]
@andersdd - what's the status of this pull request?

**Comment by andersdd** [comment]
@gilmoskowitz The PR resolves the original issue but ZenQ found another latent bug.  I have traced the crash back to a function SQL which looks like it is locking itself (??) and thus not returning and causing the guiclient to segfault.   Not found the root cause of the issue as yet, but it is a bit of an edge case.

**Pull request merged**
