### PR TITLE
issue #28747 - fixed problems that prevented proper database building

### PR DESCRIPTION
**Pull request by ChristopherCotnoir**

### CODE REVIEW

**Comment by bendiy** [comment]
@ChristopherCotnoir Still getting a CI error:
```
################################################################################
# ERROR: psql stderr OUTPUT LAST 20 LINES OF: /home/travis/build/xtuple/xtuple/scripts/output/build_dev.sql.log
################################################################################
 psql:/home/travis/build/xtuple/xtuple/scripts/output/build_dev.sql:65800: ERROR:  record "_current" has no field "default"
LINE 1: SELECT (_current.default is not null and _current.default!=c...
                ^
QUERY:  SELECT (_current.default is not null and _current.default!=constraint_text and lower(constraint_text)!='primary key')
CONTEXT:  PL/pgSQL function xt.add_column(text,text,text,text,text,text) line 52 at IF
 
################################################################################
# END OF psql stderr LOG OUTPUT ################################################
################################################################################
```
https://travis-ci.org/xtuple/xtuple/builds/169574178#L992

**Comment by davidbeauchamp** [comment]
I think default is a reserved word for all PostgreSQL versions btw (since its the placeholder for the value specified as default on the column definition)

**Comment by ChristopherCotnoir** [comment]
npm run-script test-build worked for me with this code for 9.5, but not 9.3. So 9.5 at least handles it somehow.

**Comment by gilmoskowitz** [comment]
@ChristopherCotnoir - merging so QA can get unblocked. CI is still failing on the item barcode test

**Pull request merged**
