### PR TITLE
Issue #28408: Correct data type bug in getcompanyid function

### PR DESCRIPTION
**Pull request by andersdd**
Function assumes company is a integer value instead of alphanumeric

### CODE REVIEW

**Comment by sindhupriyaav** [comment]
Performed UAT: Created company '1A' and executed 'SELECT getcompanyid(1A)' in database. Observed following error. 

ERROR:  syntax error at or near "A"
LINE 2: 1A
         ^
********** Error **********

ERROR: syntax error at or near "A"
SQL state: 42601
Character: 23

**Comment by davidbeauchamp** [comment]
@sindhupriyaav I believe you need to pass in an accnt_id from the accnt table, and it will return the company id, so "SELECT getcompanyid(109)" should return "01" from the demo databases.

**Comment by andersdd** [comment]
@sindhupriyaav @davidbeauchamp  Actually it should return the company internal id so return 1 not '01'

The original error was assuming the accnt_company and company_code where always integers when in fact they are text fields

**Comment by lokeshsh** [comment]
Performed UAT: Issue is fixed

**Pull request merged**
