### PR TITLE
[29457] Extend sales order history to include originating coitem_id, invchead_id, invcitem_id where applicable

### PR DESCRIPTION
**Pull request by davidbeauchamp**
Sales lines include all three, Misc items (sales categories) include invchead_id and invcitem_id, freight and misc charge only have invchead_id

### CODE REVIEW

**Comment by rkannadevara** [comment]
Performed UAT: Observed that coitem_id, invchead_id and invcitem_id in 'cohist' table and observed the following behavior:

1. Created a sales order, issued to shipping and posted the invoice. Observed that two rows are created in 'cohist' table: In first row, all three coitem_id, invchead_id and invcitem_id values are populated. In second row, only 'invchead_id' value is populated.

2. Created and posted a miscellaneous invoice. Observed that one row is created with invchead_id and invcitem_id are populated.

**Comment by davidbeauchamp** [comment]
If that first posting had a miscellaneous charge or freight on the invoice then that looks good. Freight and Misc. Charges create additional postings in cohist.

**Comment by sindhupriyaav** [comment]
Performed UAT: Issue is fixed.

**Comment by gilmoskowitz** [comment]
`grep` shows that the following also `insert into cohist`:
- [createARCreditMemo()](https://github.com/xtuple/xtuple/blob/4_11_x/foundation-database/public/functions/createarcreditmemo.sql)
- [createARDebitMemo()](https://github.com/xtuple/xtuple/blob/4_11_x/foundation-database/public/functions/createardebitmemo.sql)
- [postCreditMemo()](https://github.com/xtuple/xtuple/blob/4_11_x/foundation-database/public/functions/postcreditmemo.sql)
- [restoreSalesHistory()](https://github.com/xtuple/xtuple/blob/4_11_x/foundation-database/public/functions/restoresaleshistory.sql)

Certainly restoreSalesHistory() needs to be updated along with [archiveSalesHistory()](https://github.com/xtuple/xtuple/blob/4_11_x/foundation-database/public/functions/archivesaleshistory.sql). The others bear investigation.

**Comment by xtuple-ci-user** [comment]
Build finished.

**Comment by gilmoskowitz** [comment]
jenkins - retest this please

**Comment by ChristopherCotnoir** [comment]
jenkins - retest this please

**Comment by davidbeauchamp** [comment]
Added columns to `asohist` and modified `archivesaleshistory` and `restoresaleshistory` to include the new columns. Did not make modifications to `createardebitmemo`, `createarcreditmemo`,  while they insert into `cohist` none of them are directly linked to a sales order or invoice. Modified `postcreditmemo` to insert  `invchead_id` from whatever `invcnumber` was given to the credit memo.

**Pull request merged**
