### PR TITLE
[32113] Fix ability to post unprinted payments.  

### PR DESCRIPTION
**Pull request by andersdd**
Notify user when no valid payments to post.

Additional checks on payment status.  Resolved latent sql bugs when posting payments.

### CODE REVIEW

**Comment by andersdd** [comment]
@ChristopherCotnoir I found some sql bugs in the postcheck() function introduced in your last PR.  Can you please review this PR to make sure I have corrected these properly.

**Comment by gilmoskowitz** [comment]
CI is failing because the rule is being enforced:
```
RAISE EXCEPTION 'This payment must be printed before posting [xtuple: postCheck, -9, %]', pcheckid;
```
Either the test or demo data need to set the bank account to allow posting unprinted checks.

**Comment by ChristopherCotnoir** [comment]
jenkins - retest this please

**Comment by ChristopherCotnoir** [comment]
jenkins - retest this please

**Comment by ChristopherCotnoir** [comment]
The voidPostedCheck test also needs updating for the same reason as the bankrec test.

**Comment by andersdd** [comment]
jenkins - retest this please

**Comment by andersdd** [comment]
jenkins - retest this please

**Comment by lalithapadala** [comment]
Performed UAT: Observed that user is unable to post the payment which is not printed. 'There are no valid payments to post' dialog box is displayed on trying to post the non-printed payment. Also observed that printed payment is posted successfully.

**Comment by ChristopherCotnoir** [comment]
jenkins - retest this please

**Pull request merged**
