### PR TITLE
Update checkprivilege function to handle superuser check and check ALL

### PR DESCRIPTION
**Pull request by andersdd**
check for ALL privileges assigned.

### CODE REVIEW

**Comment by gilmoskowitz** [comment]
jenkins - retest this please

**Comment by gilmoskowitz** [comment]
jenkins - retest this please

**Comment by gilmoskowitz** [comment]
jenkins - retest this please

**Comment by gilmoskowitz** [comment]
jenkins - retest this please

**Comment by andersdd** [comment]
jenkins - retest this please

**Comment by gilmoskowitz** [comment]
jenkins - retest this please
now that 4_12_x has been merged in

**Pull request merged**
