### PR TITLE
Issue #29701: Demo Database data fixes

### PR DESCRIPTION
**Pull request by andersdd**
Turn CBUMP sold flag off.
Remove dodgy temporary invoice.

### CODE REVIEW

**Comment by gilmoskowitz** [comment]
jenkins - retest this please

**Comment by gilmoskowitz** [comment]
Jenkins testing failed in the same place both times:
```
 ✖ 1 of 2592 tests failed:

  1) XM.Printer test Invoice print tests Navigate to Billing > Invoice list and print:
     expected false to be true
```

**Comment by andersdd** [comment]
Given the trival and unrelated nature of the changes in this PR - do you know why that might occur?

**Comment by gilmoskowitz** [comment]
I don't have any good ideas. It's remotely possible that the test is trying to print an invoice for a CBUMP.

**Comment by andersdd** [comment]
No idea why it is failing.  XM.Printer test passes when run locally and I can see no relationship between the changes and the invoice printing.
selection_010

**Comment by gilmoskowitz** [comment]
jenkins - retest this please

**Pull request merged**
