### PR TITLE
issue #28868 Always use exchange rate between base currency and bank account currency

### PR DESCRIPTION
**Pull request by ChristopherCotnoir**

### CODE REVIEW

**Comment by sindhupriyaav** [comment]
Performed UAT  and please find the below observations.

Before clearing : Base Amount : 1879.07 and Amount : 1879.07 in USD

After clearing : Base Amount : 1879.07 in USD and Amount : 1204.53 in GBP

**Comment by ChristopherCotnoir** [comment]
Exactly what process was used to get that result? What currency were the invoice, cash receipt, and bank account in, what was the base currency of the system, and what amounts were used on the invoice and cash receipt?

**Comment by sindhupriyaav** [comment]
1. Created and posted an invoice for foreign currency customer (XTRM) and item (YTRUCK1) and invoice amount is '1204.53 GBP' and in base currency : 1879.07 USD.

2. Created and posted a cash receipt for foreign currency customer (XTRM) with amount '1204.53 GBP'  into USD bank account ('EBANK - eBank Checking Account') for above created invoice.

3. Opened 'Reconcile Bank Account' screen and observed the below behavior:

      Before Clearing, 'Base Amount' value  is displayed as '1879.07' and 'Amount' value is displayed as '1879.07'.

      After clearing,  'Base Amount' value  is displayed as '1879.07' and 'Amount' value is displayed as '1204.53'.

Please note that Base currency is in 'USD'.

**Comment by ChristopherCotnoir** [comment]
Unable to reproduce the problem. Following those steps without this pull request that result occurs, but with this pull request the 'Amount' value is still '1879.07' after clearing. Please retest with a fresh database and ensure it is up to date and includes these changes. If the problem still occurs, go to System->Design->MetaSQL Statements and ensure the text for bankrec-checks and bankrec-receipts matches the files as of these changes.

**Comment by lokeshsh** [comment]
Performed UAT: Issue is fixed

**Pull request merged**
