### PR TITLE
Issue #29408: Deleting Std cost did not update itemsite or history

### PR DESCRIPTION
**Pull request by andersdd**
This was a timing issue with calculating Std Cost.  Also affected the GL postings and Inventory History (not mentioned in original issue).

### CODE REVIEW

**Comment by lokeshsh** [comment]
Performed UAT: Please find the steps below:
Deleted the Standard cost for the item say 'Sheet1' from 'Maintain Item Costs' screen and observed that the value of 'itemsite_value' in the 'item site' table is not updated to '0'

**Comment by gilmoskowitz** [comment]
@andersdd - the code looks correct but the UAT says otherwise. any ideas? this might be a good time to add unit tests for this function.

**Comment by andersdd** [comment]
@gilmoskowitz @lokeshsh  UAT was correct.  The original change did correctly update std cost but not the Item Site.  I have corrected the function to correctly update both areas of cost.

**Comment by andersdd** [comment]
@gilmoskowitz  I was just reviewing the current updateitemcost test and it looks wrong.  I don't know how it is passing as the wrong parameters are being passed into the function by the test.  Do you want me to go through and 'fix' it?

**Comment by gilmoskowitz** [comment]
@andersdd - If you have time, fixing the test would be very helpful.

**Pull request merged**
