### PR TITLE
Issue #30466: Incident delete sql bug

### PR DESCRIPTION
**Pull request by andersdd**

### CODE REVIEW

**Comment by harithamekala** [comment]
Performed UAT: Issue is fixed when parent recurring invoice with 'Days' is edited. But observed db log error while editing parent recurring invoice with 'Days', 'Months', 'Years', 'Minutes' and 'Years'. Please refer the below provided DB log error:

Mon Jul 17 18:47:58 2017 Debug: Looking for scripts ("QObject", "QWidget", "XWidget", "display", "incidentWorkbench")
Mon Jul 17 18:47:58 2017 Debug: Looking for scripts ("QObject", "QWidget", "VirtualCluster", "UsernameCluster", "widget2")
Mon Jul 17 18:47:58 2017 Debug: Looking for scripts ("QObject", "QWidget", "VirtualCluster", "UsernameCluster", "widget2")
Mon Jul 17 18:48:01 2017 Debug: Documents::addToMap( 83 ,  "" ) duplicate!
Mon Jul 17 18:48:01 2017 Debug: Documents::addToMap( 148 ,  "" ) duplicate!
Mon Jul 17 18:48:01 2017 Debug: Documents::addToMap( 150 ,  "" ) duplicate!
Mon Jul 17 18:48:01 2017 Debug: Documents::addToMap( 164 ,  "" ) duplicate!
Mon Jul 17 18:48:01 2017 Debug: Looking for scripts ("QObject", "QWidget", "QDialog", "XDialog", "incident")
Mon Jul 17 18:48:01 2017 Warning: Column owner not found in record
Mon Jul 17 18:48:01 2017 Debug: Looking for scripts ("QObject", "QWidget", "VirtualCluster", "CRMAcctCluster", "_crmacct")
Mon Jul 17 18:48:01 2017 Debug: Looking for scripts ("QObject", "QWidget", "VirtualCluster", "UsernameCluster", "_owner")
Mon Jul 17 18:48:01 2017 Debug: Looking for scripts ("QObject", "QWidget", "VirtualCluster", "UsernameCluster", "_assignedTo")
Mon Jul 17 18:48:01 2017 Debug: Looking for scripts ("QObject", "QWidget", "VirtualCluster", "ContactCluster", "_cntct")
Mon Jul 17 18:48:01 2017 Debug: Looking for scripts ("QObject", "QWidget", "VirtualCluster", "ProjectCluster", "_project")
Mon Jul 17 18:48:03 2017 Debug: Looking for scripts ("QObject", "QWidget", "VirtualCluster", "ItemCluster", "_item")
Mon Jul 17 18:48:03 2017 Debug: Looking for scripts ("QObject", "QWidget", "VirtualCluster", "LotserialCluster", "_lotserial")
Mon Jul 17 18:48:11 2017 ERROR:  update or delete on table "incdt" violates foreign key constraint "incdt_incdt_recurring_incdt_id_fkey" on table "incdt"
DETAIL:  Key (incdt_id)=(11) is still referenced from table "incdt".
CONTEXT:  SQL statement "DELETE FROM incdt
    WHERE (incdt_id=pincdtid)"
PL/pgSQL function deleteincident(integer) line 35 at SQL statement
SQL statement "
                          SELECT deleteincident(incdt_id) FROM incdt
                          
                           WHERE (('11'=incdt_recurring_incdt_id)
                           AND (TRUE)
                           
                           AND NOT(incdt_status IN ('R', 'L'))
                         
                           
                           AND (incdt_timestamp<'2017-07-17 18:48:00+05:30')
                         
                           );
                         
                        "
PL/pgSQL function createrecurringitems(integer,text) line 283 at EXECUTE statement
(23503) QPSQL: Unable to create query
SELECT createRecurringItems(11, 'INCDT')       AS result;
Mon Jul 17 18:48:11 2017 Warning: ERROR:  update or delete on table "incdt" violates foreign key constraint "incdt_incdt_recurring_incdt_id_fkey" on table "incdt"
DETAIL:  Key (incdt_id)=(11) is still referenced from table "incdt".
CONTEXT:  SQL statement "DELETE FROM incdt
    WHERE (incdt_id=pincdtid)"
PL/pgSQL function deleteincident(integer) line 35 at SQL statement
SQL statement "
                          SELECT deleteincident(incdt_id) FROM incdt
                          
                           WHERE (('11'=incdt_recurring_incdt_id)
                           AND (TRUE)
                           
                           AND NOT(incdt_status IN ('R', 'L'))
                         
                           
                           AND (incdt_timestamp<'2017-07-17 18:48:00+05:30')
                         
                           );
                         
                        "
PL/pgSQL function createrecurringitems(integer,text) line 283 at EXECUTE statement
(23503) QPSQL: Unable to create query
Mon Jul 17 18:48:13 2017 Debug: Looking for scripts ("QObject", "QWidget", "QMainWindow", "XMainWindow", "submitEDI")
Mon Jul 17 18:48:13 2017 Debug: Looking for scripts ("QObject", "QWidget", "VirtualCluster", "IncidentCluster", "_incdt")

**Comment by harithamekala** [comment]
Performed UAT: Issue is fixed when parent recurring invoice with 'Days' is edited. But observed db log error while editing parent recurring invoice with 'Days', 'Months', 'Years', 'Minutes' and 'Years'. Please refer the below provided DB log error:

Mon Jul 17 18:49:19 2017 Debug: Looking for scripts ("QObject", "QWidget", "QDialog", "XDialog", "incident")
Mon Jul 17 18:49:19 2017 Warning: Column owner not found in record
Mon Jul 17 18:49:19 2017 Debug: Looking for scripts ("QObject", "QWidget", "VirtualCluster", "CRMAcctCluster", "_crmacct")
Mon Jul 17 18:49:19 2017 Debug: Looking for scripts ("QObject", "QWidget", "VirtualCluster", "UsernameCluster", "_owner")
Mon Jul 17 18:49:19 2017 Debug: Looking for scripts ("QObject", "QWidget", "VirtualCluster", "UsernameCluster", "_assignedTo")
Mon Jul 17 18:49:19 2017 Debug: Looking for scripts ("QObject", "QWidget", "VirtualCluster", "ContactCluster", "_cntct")
Mon Jul 17 18:49:19 2017 Debug: Looking for scripts ("QObject", "QWidget", "VirtualCluster", "ProjectCluster", "_project")
Mon Jul 17 18:49:22 2017 Debug: Looking for scripts ("QObject", "QWidget", "VirtualCluster", "ItemCluster", "_item")
Mon Jul 17 18:49:22 2017 Debug: Looking for scripts ("QObject", "QWidget", "VirtualCluster", "LotserialCluster", "_lotserial")
Mon Jul 17 18:49:27 2017 ERROR:  update or delete on table "incdt" violates foreign key constraint "incdt_incdt_recurring_incdt_id_fkey" on table "incdt"
DETAIL:  Key (incdt_id)=(11) is still referenced from table "incdt".
CONTEXT:  SQL statement "DELETE FROM incdt
    WHERE (incdt_id=pincdtid)"
PL/pgSQL function deleteincident(integer) line 35 at SQL statement
SQL statement "
                          SELECT deleteincident(incdt_id) FROM incdt
                          
                           WHERE (('11'=incdt_recurring_incdt_id)
                           AND (TRUE)
                           
                           AND NOT(incdt_status IN ('R', 'L'))
                         
                           
                           AND (incdt_timestamp<'2017-07-17 18:49:00+05:30')
                         
                           );
                         
                        "
PL/pgSQL function createrecurringitems(integer,text) line 283 at EXECUTE statement
(23503) QPSQL: Unable to create query
SELECT createRecurringItems(11, 'INCDT')       AS result;
Mon Jul 17 18:49:27 2017 Warning: ERROR:  update or delete on table "incdt" violates foreign key constraint "incdt_incdt_recurring_incdt_id_fkey" on table "incdt"
DETAIL:  Key (incdt_id)=(11) is still referenced from table "incdt".
CONTEXT:  SQL statement "DELETE FROM incdt
    WHERE (incdt_id=pincdtid)"
PL/pgSQL function deleteincident(integer) line 35 at SQL statement
SQL statement "
                          SELECT deleteincident(incdt_id) FROM incdt
                          
                           WHERE (('11'=incdt_recurring_incdt_id)
                           AND (TRUE)
                           
                           AND NOT(incdt_status IN ('R', 'L'))
                         
                           
                           AND (incdt_timestamp<'2017-07-17 18:49:00+05:30')
                         
                           );
                         
                        "
PL/pgSQL function createrecurringitems(integer,text) line 283 at EXECUTE statement
(23503) QPSQL: Unable to create query

**Comment by andersdd** [comment]
@harithamekala You will have to provide more details.  I managed to edit the recurring Invoice without seeing any errors.  The error log you have provided all relate to Incidents not Invoices so it is possible you are encountering a bug elsewhere.

**Comment by harithamekala** [comment]
Tested in xTuple 4.11.0 RC latest nightly build (2017-07-17): Please find the below steps to reproduce the issue:

1. Create a new incident with Recurring 'Days' of value 'Create no more than' as '3'.

2. Ensure that total 3 incidents should be created (1 parent and 2 Child incidents).

3. Now select parent incident and click on 'Edit' option from context menu.

4. Navigate to 'Relationships' tab, Change 'Days' to 'Years' and click on 'Save' button.

5. Click on 'Yes' button in 'Change Open Events' window.

6. Observe that db log error is displayed and incident is not saved. Please refer the attached screenshot 'RecurringIncident.png' and 'DB Log Error.txt'

recurringincident

[DB Log Error.txt](https://github.com/xtuple/xtuple/files/1155634/DB.Log.Error.txt)

**Comment by andersdd** [comment]
@harithamekala Please retest.  I cannot reproduce the error, but think that is due to a related fix posted in recent days which you might not have yet built into your test system.

**Pull request merged**
