### PR TITLE
Add subnumber to invoice

### PR DESCRIPTION
**Pull request by ChristopherCotnoir**

### CODE REVIEW

**Comment by ChristopherCotnoir** [comment]
Associated with xtuple/enhanced-pricing#30

**Comment by jcarlin** [comment]
Add `item_type`? Sales Order and Quote item list metasql both have it. Also, is `soitemnumber` sufficient for a formatted subnumber column (it uses `coitem_subnumber`) or should there be a new formatted sub number column using `invcitem_subnumber` as well? i.e. https://github.com/xtuple/xtuple/pull/3055/files

**Comment by ChristopherCotnoir** [comment]
There is no point in adding columns to the metasql if the client isn't looking for those columns. Remember that invoices are different from Sales Orders and Quotes, which are much more similar to each other, it is expected that the columns will not be the same. You can ask Ben, but I'm pretty sure using coitem's formatting is fine.

**Comment by jcarlin** [comment]
OK. We _will_ need new formatting when we allow discount codes on invoices without sales orders.

**Pull request merged**
