### PR TITLE
Issue #17965: Remove obsolete cohead_type column

### PR DESCRIPTION
**Pull request by andersdd**

### CODE REVIEW

**Comment by davidbeauchamp** [comment]
Something about doing this doesn't feel right, will this mess up peoples historical data? (Was there a migration path to move what was in here into the salestype table?)

**Comment by andersdd** [comment]
Wont touch the table if there is any data in the cohead_type field

**Comment by davidbeauchamp** [comment]
Ahh, gotcha.

**Comment by rkannadevara** [comment]
Unable to perform UAT: Observed the below error while building the database from pull request branch:

Saved PEGjs parser Javascript to  ../lib/orm/source/xt/javascript/parseediprofile.sql
undefined undefined 'Error in manifest vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv\nError: /home/xtuple/src/xtuple/foundation-database/public/tables/cohead.sql contents do not end in a semicolon.\nError in manifest ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^'
Error in manifest vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
Error: /home/xtuple/src/xtuple/foundation-database/public/tables/cohead.sql contents do not end in a semicolon.
Error in manifest ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by sindhupriyaav** [comment]
Performed UAT and observed that cohead_type column is displayed in cohead table.

Please refer to attachment.

**Comment by sindhupriyaav** [comment]
@andersdd Thank you for providing information.

Performed UAT and observed that cohead_type coulmn is displayed if any data is available for cohead_type. Please refer to attachment.
cohead_type

Could you please let me know the how to verify the scenario - cohead_type coulmn should be removed if no data is available in cohed_type?

**Comment by andersdd** [comment]
@sindhupriyaav  run the foolowing code on your database to empty the column then try testing this change

```UPDATE cohead SET cohead_type = NULL;```

**Comment by lokeshsh** [comment]
Performed UAT: 
1. Created a database in pgAdmin using '4.10.0 masterref' backup file and observed that on running the below query 'cohead_type' column becomes "Null"
"UPDATE cohead SET cohead_type = NULL;" 
2. Now performed build_app on the the above database from pull request  branch.
3. Observed that 'cohead_type' column  is not been removed.

####Please refer the attached screenshot#### 
pull request

**Comment by andersdd** [comment]
@lokeshsh please test again.  There was some dependencies with the mobile client that required tidying up.

**Comment by rkannadevara** [comment]
Performed UAT: Issue is fixed. Observed that 'cohead_type' column is not available when it is NULL in 'cohead' table.

**Pull request merged**
