### PR TITLE
issue #29303 - Handle empty Document Reference when reversing AR applications

### PR DESCRIPTION
**Pull request by andersdd**

### CODE REVIEW

**Comment by harithamekala** [comment]
Performed UAT:Issue still exsists.Created & posted a cash receipt without providing document number and observed an error dialog 'Error Reversing A/R Application' message saying 'You must enter a valid Document # for this AR memo' is displayed when tried to reverse the application from AR applications screen.

**Comment by gilmoskowitz** [comment]
After loading the revised version of the function, I see something different than @harithamekala 

- create a new cash receipt with an empty Payment/Document #, apply it, post it on saving
- **Accounting > Accounts Receivable > Reports > Applications**
- set date range to include current date and **Query**
- right-click on the cash receipt application, select **Reverse Application**, and get dialog `A/R Application has been reversed.` (so far, so good)
- right-click on the new reversal line, select **Reverse Application**, and get the following:
```
ERROR:  This Document Type/Number already exists. You may not enter a duplicate A/R Memo.
CONTEXT:  SQL statement "INSERT INTO aropen(
            aropen_docdate, aropen_duedate,  aropen_cust_id,
 ...
```
Based on the bug comment `Sun Apr 9 18:04:30 2017 General anderson` this re-reversal is expected to work without error.

**Comment by lokeshsh** [comment]
Performed UAT: Issue still exists.
Created & posted a cash receipt without providing document number and when tried to reverse the application from 'AR applications' screen. observed that an error dialog 'Error Reversing A/R Application' message saying 'You must enter a valid Document # for this AR memo' is displayed.

reverse_cashreceipt

**Comment by andersdd** [comment]
@lokeshsh If you apply the function in this PR the error you mention does not occur.

@gilmoskowitz I have added in an increment if you are reversing reversals so the error you found is no longer present.

**Comment by harithamekala** [comment]
Performed UAT: Issue still exists.
Created & posted a cash receipt without providing document number and when tried to reverse the application from 'AR applications' screen. observed that an error dialog 'Error Reversing A/R Application' message saying 'You must enter a valid Document # for this AR memo' is displayed
reverse

**Comment by gilmoskowitz** [comment]
jenkins - retest this please

**Pull request merged**
