### PR TITLE
Fixes Issue #24953 Allow both Vendor Address and Contact Address i

### PR DESCRIPTION
**Pull request by andersdd**
Fixes Vendor List address issue #24953

Tested on PostgreSQL 9.3 system.  Approach may need testing on a 9.1 Db system to confirm that it works on the Db version.

### CODE REVIEW

**Comment by ssshyam** [comment]
Performed UAT on Postgre SQL 9.1 and 9.3: Observed that Vendor main address details are not displayed if no contact is assigned  to it.

**Comment by shackbarth** [comment]
@ssshyam so, this PR *failed* the UAT, right?

@andersdd can you try upmerging 4_8_x and repushing? (Or request it against 4_9_x after a merge into there). There's a TravisCI problem that should be fixed by now in the mainlines.

**Comment by andersdd** [comment]
@ssshyam You need to install the metaSQL vendor-detail.mql associated with this PR.  

Unit testing shows the Vendor Address is prioritised.  If no Vendor Address exists, the primary contact address is used.  I tested all possible scenarios and observed the Vendor List always had the correct address.

@shackbarth this PR should ideally now go into 4.9_x  Should I close this PR and re-submit against the 4.9.x branch ?

**Comment by ssshyam** [comment]
Hi Anderson,

We have performed the UAT by installing the Vendors-Detail.mql file of this PR and observed that main address details of the vendor is not displayed, if no contact is assigned. 
Please let me know, if i miss anything.

Regards,
Shyam

**Comment by shackbarth** [comment]
@andersdd it's fine in 4_8_x. We'll merge forward, and if we publish a 4.8.1 it'll be nice that it's in here.

**Pull request merged**
