### PR TITLE
issue #28276 - update models so ci can pass

### PR DESCRIPTION
**Pull request by gilmoskowitz**

### CODE REVIEW

**Comment by rkannadevara** [comment]
Performed UAT: Observed the below error while building masterref database from pull request branch:

Applying build to database 28276.1
Cannot install file  /home/xtuple/src/xtuple/scripts/output/build_28276.1.sql
See errors in  /home/xtuple/src/xtuple/scripts/output/build_28276.1.sql.log

################################################################################
# ERROR: psql stderr OUTPUT LAST 20 LINES OF: /home/xtuple/src/xtuple/scripts/output/build_28276.1.sql.log
################################################################################

 psql:/home/xtuple/src/xtuple/scripts/output/build_28276.1.sql:775357: NOTICE:  installing XM.Invoice
psql:/home/xtuple/src/xtuple/scripts/output/build_28276.1.sql:775358: NOTICE:  trigger "invcheadinfo_did_change" for table "xt.invcheadinfo" does not exist, skipping
CONTEXT:  SQL statement "drop trigger if exists invcheadinfo_did_change on xt.invcheadinfo;"
SQL statement "insert into xt.orm ( orm_namespace, orm_type, orm_context, orm_json, orm_seq, orm_ext, orm_rest ) values ($1, $2, $3, $4, $5, $6, $7)"
psql:/home/xtuple/src/xtuple/scripts/output/build_28276.1.sql:775358: INFO:  {"code":200,"message":"OK"}
psql:/home/xtuple/src/xtuple/scripts/output/build_28276.1.sql:775359: NOTICE:  installing (extension inventory) XM.Invoice
psql:/home/xtuple/src/xtuple/scripts/output/build_28276.1.sql:775360: INFO:  {"code":200,"message":"OK"}
psql:/home/xtuple/src/xtuple/scripts/output/build_28276.1.sql:775361: NOTICE:  installing XM.InvoiceLine
psql:/home/xtuple/src/xtuple/scripts/output/build_28276.1.sql:775362: NOTICE:  view "invoice_line" does not exist, skipping
CONTEXT:  SQL statement "DROP VIEW IF EXISTS xm.invoice_line CASCADE;"
PL/pgSQL function xt.create_view(text,text,boolean) line 19 at EXECUTE statement
SQL statement "SELECT xt.create_view($1, $2, false);"
SQL statement "insert into xt.orm ( orm_namespace, orm_type, orm_context, orm_json, orm_seq, orm_ext, orm_rest ) values ($1, $2, $3, $4, $5, $6, $7)"
psql:/home/xtuple/src/xtuple/scripts/output/build_28276.1.sql:775362: INFO:  {"code":500,"message":"Internal Server Error"}
psql:/home/xtuple/src/xtuple/scripts/output/build_28276.1.sql:775362: WARNING:  Error: Error: column "updateInventory" specified more than once
    at Object.XT.Orm.install (eval at <anonymous> (js_init:920:20), <anonymous>:182:12)
    at null.<anonymous> (install_orm:4:12)

psql:/home/xtuple/src/xtuple/scripts/output/build_28276.1.sql:775362: ERROR:  unhandledError
DETAIL:  js_init() LINE 372:       throw "unhandledError";
 
################################################################################
# END OF psql stderr LOG OUTPUT ################################################
################################################################################


Command failed:  Error: Command failed: 
    at ChildProcess.exithandler (child_process.js:658:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5) { [Error: Command failed: ] killed: false, code: 3, signal: null }
{ [Error: Command failed: ] killed: false, code: 3, signal: null }

**Comment by gilmoskowitz** [comment]
https://github.com/xtuple/private-extensions/pull/956 should fix the buildapp failures

**Comment by gilmoskowitz** [comment]
jenkins - retest this please

**Comment by rkannadevara** [comment]
Performed UAT: Issue is fixed. Please refer the below attached screenshot:

invcitem

**Pull request merged**
